//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.TickerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TickerService.ITicker", CallbackContract=typeof(client.TickerService.ITickerCallback))]
    public interface ITicker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicker/Register", ReplyAction="http://tempuri.org/ITicker/RegisterResponse")]
        void Register();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicker/Register", ReplyAction="http://tempuri.org/ITicker/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicker/Unregister", ReplyAction="http://tempuri.org/ITicker/UnregisterResponse")]
        void Unregister();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicker/Unregister", ReplyAction="http://tempuri.org/ITicker/UnregisterResponse")]
        System.Threading.Tasks.Task UnregisterAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITickerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicker/OnAlert", ReplyAction="http://tempuri.org/ITicker/OnAlertResponse")]
        void OnAlert(System.DateTime time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITickerChannel : client.TickerService.ITicker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TickerClient : System.ServiceModel.DuplexClientBase<client.TickerService.ITicker>, client.TickerService.ITicker {
        
        public TickerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TickerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TickerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TickerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TickerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Register() {
            base.Channel.Register();
        }
        
        public System.Threading.Tasks.Task RegisterAsync() {
            return base.Channel.RegisterAsync();
        }
        
        public void Unregister() {
            base.Channel.Unregister();
        }
        
        public System.Threading.Tasks.Task UnregisterAsync() {
            return base.Channel.UnregisterAsync();
        }
    }
}
